[tool.ruff]
line-length = 200
extend-exclude = ['migrations', 'manage.py']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']
ignore = ['E501', 'PLR0917', 'PLR0913', 'PLR6301']  # Ignora o erro de linha muito longa e o de muitos argumentos posicionais

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
lint = 'ruff check .'
format = 'ruff check --fix && ruff format .'
run = 'uvicorn app.main:app --reload'
test = 'pytest'
post_test = 'coverage html'